from pathlib import Path


WORKSPACE_ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = [
    "README.md",
    "PROJECT_STRUCTURE.md",
    "ENVIRONMENT.md",
    "GIT_STRATEGY.md",
    ".gitignore",
    "docs/ROADMAP.md",
    "docs/SYSTEM_ARCHITECTURE.md",
    "docs/MODULE_BOUNDARY.md",
    "docs/VEHICLE_TYPE_INTERFACE.md",
    "docs/IMAGE_INPUT_FLOW.md",
    "docs/YOLO_DETECTION_FLOW.md",
    "docs/VEHICLE_TYPE_DATASET_PLAN.md",
    "docs/VEHICLE_TYPE_DATASET_REBUILD.md",
    "docs/VEHICLE_TYPE_DATASET_SPLIT.md",
    "docs/VEHICLE_TYPE_SPLIT_REVIEW.md",
    "docs/VEHICLE_TYPE_CLASSIFIER_TRAINING.md",
    "docs/VEHICLE_TYPE_CLASSIFY_PIPELINE.md",
    "docs/AICAR_SIM_VEHICLE_MODEL_SELECTION.md",
    "docs/STAGE1_VEHICLE_RECOGNITION_SUMMARY.md",
    "docs/PROJECT_DIRECTORY_STRATEGY.md",
    "docs/INDEX.md",
    "docs/MODEL_ARTIFACTS.md",
    "docs/STAGE1_FINAL_FIX_NOTES.md",
    "docs/IMAGE_PREPROCESSING_FLOW.md",
    "docs/OPEN_SOURCE_REVIEW_PLAN.md",
    "docs/DATASET_PLAN.md",
    "docs/MODEL_PLAN.md",
    "docs/COLLABORATION_NOTES.md",
    "aicar_sim/README.md",
    "aicar_sim/requirements.txt",
    "aicar_sim/pyproject.toml",
    "aicar_sim/config/sim_config.yaml",
    "aicar_sim/config/wash_recipe_basic.yaml",
    "aicar_sim/data/vehicles/sedan.json",
    "aicar_sim/data/vehicles/suv.json",
    "aicar_sim/data/vehicles/mpv.json",
    "aicar_sim/scripts/run_sim.ps1",
    "aicar_sim/scripts/check_sim_structure.py",
    "aicar_sim/scripts/check_vehicle_type_input.py",
    "aicar_sim/scripts/check_vehicle_model_selection.py",
    "aicar_sim/scripts/check_all_vehicle_model_selection.py",
    "aicar_sim/src/aicar_sim/__init__.py",
    "aicar_sim/src/aicar_sim/main.py",
    "aicar_sim/src/aicar_sim/vehicle_model.py",
    "aicar_sim/src/aicar_sim/path_planner.py",
    "aicar_sim/src/aicar_sim/wash_state_machine.py",
    "aicar_sim/src/aicar_sim/nozzle_controller.py",
    "aicar_sim/src/aicar_sim/plc_interface.py",
    "aicar_sim/src/aicar_sim/safety_monitor.py",
    "aicar_sim/src/aicar_sim/visualizer_pygame.py",
    "aicar_sim/src/aicar_sim/schemas.py",
    "aicar_sim/src/aicar_sim/vehicle_type_input.py",
    "aicar_sim/tests/test_structure.py",
    "aicar_sim/tests/fixtures/vehicle_type_result_sedan.json",
    "aicar_sim/tests/fixtures/vehicle_type_result_suv.json",
    "aicar_sim/tests/fixtures/vehicle_type_result_mpv.json",
    "aicar_sim/tests/fixtures/vehicle_type_result_unknown.json",
    "vehicle_type_lab/README.md",
    "vehicle_type_lab/requirements.txt",
    "vehicle_type_lab/pyproject.toml",
    "vehicle_type_lab/config/vehicle_type_config.yaml",
    "vehicle_type_lab/data/input_images/.gitkeep",
    "vehicle_type_lab/data/input_images/README.md",
    "vehicle_type_lab/data/sample_images/README.md",
    "vehicle_type_lab/data/datasets/README.md",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/README.md",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/CLASS_DEFINITION.md",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/NAMING_RULES.md",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/incoming/sedan/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/incoming/suv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/incoming/mpv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/raw/sedan/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/raw/suv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/raw/mpv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/split/train/sedan/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/split/train/suv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/split/train/mpv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/split/val/sedan/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/split/val/suv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/split/val/mpv/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/review/.gitkeep",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/manifests/README.md",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/manifests/dataset_manifest_template.csv",
    "vehicle_type_lab/data/datasets/vehicle_type_classification/manifests/split_manifest.csv",
    "vehicle_type_lab/data/annotations/README.md",
    "vehicle_type_lab/models/pretrained/.gitkeep",
    "vehicle_type_lab/models/trained/.gitkeep",
    "vehicle_type_lab/models/exported/.gitkeep",
    "vehicle_type_lab/models/vehicle_type_classifier/.gitkeep",
    "vehicle_type_lab/outputs/predictions/.gitkeep",
    "vehicle_type_lab/outputs/predictions/history/.gitkeep",
    "vehicle_type_lab/outputs/predictions/visualized/.gitkeep",
    "vehicle_type_lab/outputs/predictions/crops/.gitkeep",
    "vehicle_type_lab/outputs/reports/.gitkeep",
    "vehicle_type_lab/outputs/training/vehicle_type_classifier/.gitkeep",
    "vehicle_type_lab/outputs/training/vehicle_type_classifier/runs/.gitkeep",
    "vehicle_type_lab/outputs/training/vehicle_type_classifier/reports/.gitkeep",
    "vehicle_type_lab/scripts/run_detect_demo.ps1",
    "vehicle_type_lab/scripts/check_lab_structure.py",
    "vehicle_type_lab/scripts/check_interface.py",
    "vehicle_type_lab/scripts/check_image_input.py",
    "vehicle_type_lab/scripts/check_yolo_detect.py",
    "vehicle_type_lab/scripts/check_vehicle_type_classify.py",
    "vehicle_type_lab/scripts/check_vehicle_type_dataset.py",
    "vehicle_type_lab/scripts/prepare_vehicle_type_images.py",
    "vehicle_type_lab/scripts/split_vehicle_type_dataset.py",
    "vehicle_type_lab/scripts/make_vehicle_type_split_contact_sheets.py",
    "vehicle_type_lab/scripts/train_vehicle_type_classifier.py",
    "vehicle_type_lab/scripts/eval_vehicle_type_classifier.py",
    "vehicle_type_lab/schemas/vehicle_type_result.schema.json",
    "vehicle_type_lab/examples/result_sedan.json",
    "vehicle_type_lab/examples/result_suv.json",
    "vehicle_type_lab/examples/result_mpv.json",
    "vehicle_type_lab/examples/result_unknown.json",
    "vehicle_type_lab/src/vehicle_type_lab/__init__.py",
    "vehicle_type_lab/src/vehicle_type_lab/main.py",
    "vehicle_type_lab/src/vehicle_type_lab/mock_classifier.py",
    "vehicle_type_lab/src/vehicle_type_lab/image_io.py",
    "vehicle_type_lab/src/vehicle_type_lab/yolo_detector.py",
    "vehicle_type_lab/src/vehicle_type_lab/crop_utils.py",
    "vehicle_type_lab/src/vehicle_type_lab/vehicle_type_classifier.py",
    "vehicle_type_lab/src/vehicle_type_lab/detect_vehicle.py",
    "vehicle_type_lab/src/vehicle_type_lab/classify_vehicle_type.py",
    "vehicle_type_lab/src/vehicle_type_lab/export_result.py",
    "vehicle_type_lab/src/vehicle_type_lab/schemas.py",
    "vehicle_type_lab/src/vehicle_type_lab/utils.py",
    "vehicle_type_lab/tests/test_structure.py",
    "external_repos/README.md",
    "external_repos/clone_repos.ps1",
    "datasets/README.md",
    "datasets/raw/.gitkeep",
    "datasets/processed/.gitkeep",
    "datasets/vehicle_type/sedan/.gitkeep",
    "datasets/vehicle_type/suv/.gitkeep",
    "datasets/vehicle_type/mpv/.gitkeep",
    "datasets/annotations/.gitkeep",
    "datasets/samples/.gitkeep",
    "models/README.md",
    "models/pretrained/.gitkeep",
    "models/trained/.gitkeep",
    "models/exported/.gitkeep",
    "tools/README.md",
    "tools/setup_base_env.ps1",
    "tools/check_workspace.py",
    "tools/clean_temp_outputs.ps1",
]


def main() -> None:
    missing = [path for path in REQUIRED_PATHS if not (WORKSPACE_ROOT / path).exists()]
    if missing:
        print("Missing AI Car Wash workspace scaffold paths:")
        for path in missing:
            print(f"- {path}")
        raise SystemExit(1)

    print("AI Car Wash workspace scaffold OK")


if __name__ == "__main__":
    main()
